from django.db import models

class Producto(models.Model):
    codigo = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=100)
    barra = models.CharField(max_length=20)
    referencia = models.CharField(max_length=50)
    iva = models.DecimalField(max_digits=5, decimal_places=2)
    catalogo = models.CharField(max_length=20)
    marca = models.CharField(max_length=50)
    sub_marca = models.CharField(max_length=50)
    um = models.CharField(max_length=20)
    linea = models.CharField(max_length=20)
    desc_linea = models.CharField(max_length=50)
    categoria = models.CharField(max_length=20)
    desc_categoria = models.CharField(max_length=50)
    sub_categoria = models.CharField(max_length=20)
    desc_sub_categoria = models.CharField(max_length=50)
    existencia_total = models.CharField(max_length=20)
    pvp_base = models.DecimalField(max_digits=10, decimal_places=2)
    la_Urbina = models.IntegerField()
    la_Urbina_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    la_Yaguara = models.IntegerField()
    la_Yaguara_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    San_Diego = models.IntegerField()
    San_Diego_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    La_Limpia = models.IntegerField()
    La_Limpia_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    Barquisimeto = models.IntegerField()
    Barquisimeto_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    Turmero = models.IntegerField()
    Turmero_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    Cristal = models.IntegerField()
    Cristal_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    Charallave = models.IntegerField()
    Charallave_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    La_Guaira = models.IntegerField()
    La_Guaira_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    Lisandro = models.IntegerField()
    Lisandro_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    Rio_Lama = models.IntegerField()
    Rio_Lama_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    Santa_Teresa = models.IntegerField()
    Santa_Teresa_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    Guarenas = models.IntegerField()
    Guarenas_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    Guacara = models.IntegerField()
    Guacara_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    La_Vina = models.IntegerField()
    La_Vina_pvp = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f"{self.descripcion} - {self.codigo} - {self.marca} - {self.pvp_base}"

