# Generated by Django 5.0.2 on 2024-02-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('barra', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=50)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('catalogo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('sub_marca', models.CharField(max_length=50)),
                ('um', models.CharField(max_length=20)),
                ('linea', models.CharField(max_length=20)),
                ('desc_linea', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('desc_categoria', models.CharField(max_length=50)),
                ('sub_categoria', models.CharField(max_length=20)),
                ('desc_sub_categoria', models.CharField(max_length=50)),
                ('existencia_total', models.CharField(max_length=20)),
                ('pvp_base', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('la_Urbina', models.CharField(default='N/A', max_length=8)),
                ('la_Urbina_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('la_Yaguara', models.CharField(default='N/A', max_length=8)),
                ('la_Yaguara_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('San_Diego', models.CharField(default='N/A', max_length=8)),
                ('San_Diego_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('La_Limpia', models.CharField(default='N/A', max_length=8)),
                ('La_Limpia_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Barquisimeto', models.CharField(default='N/A', max_length=8)),
                ('Barquisimeto_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Turmero', models.CharField(default='N/A', max_length=8)),
                ('Turmero_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Cristal', models.CharField(default='N/A', max_length=8)),
                ('Cristal_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Charallave', models.CharField(default='N/A', max_length=8)),
                ('Charallave_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('La_Guaira', models.CharField(default='N/A', max_length=8)),
                ('La_Guaira_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Lisandro', models.CharField(default='N/A', max_length=8)),
                ('Lisandro_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Rio_Lama', models.CharField(default='N/A', max_length=8)),
                ('Rio_Lama_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Santa_Teresa', models.CharField(default='N/A', max_length=8)),
                ('Santa_Teresa_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Guarenas', models.CharField(default='N/A', max_length=8)),
                ('Guarenas_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Guacara', models.CharField(default='N/A', max_length=8)),
                ('Guacara_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('La_Vina', models.CharField(default='N/A', max_length=8)),
                ('La_Vina_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Puerto_Cabello', models.CharField(default='N/A', max_length=8)),
                ('Puerto_Cabello_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Los_Teques', models.CharField(default='N/A', max_length=8)),
                ('Los_Teques_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Ocumare_Tuy', models.CharField(default='N/A', max_length=8)),
                ('Ocumare_Tuy_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('Guaparo', models.CharField(default='N/A', max_length=8)),
                ('Guaparo_pvp', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
    ]
