# Generated by Django 5.0.2 on 2024-02-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('barra', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=50)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('catalogo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('sub_marca', models.CharField(max_length=50)),
                ('um', models.CharField(max_length=20)),
                ('linea', models.CharField(max_length=20)),
                ('desc_linea', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('desc_categoria', models.CharField(max_length=50)),
                ('sub_categoria', models.CharField(max_length=20)),
                ('desc_sub_categoria', models.CharField(max_length=50)),
                ('existencia_total', models.CharField(max_length=20)),
                ('pvp_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('la_Urbina', models.IntegerField()),
                ('la_Urbina_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('la_Yaguara', models.IntegerField()),
                ('la_Yaguara_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('San_Diego', models.IntegerField()),
                ('San_Diego_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('La_Limpia', models.IntegerField()),
                ('La_Limpia_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Barquisimeto', models.IntegerField()),
                ('Barquisimeto_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Turmero', models.IntegerField()),
                ('Turmero_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cristal', models.IntegerField()),
                ('Cristal_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Charallave', models.IntegerField()),
                ('Charallave_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('La_Guaira', models.IntegerField()),
                ('La_Guaira_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Lisandro', models.IntegerField()),
                ('Lisandro_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rio_Lama', models.IntegerField()),
                ('Rio_Lama_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Santa_Teresa', models.IntegerField()),
                ('Santa_Teresa_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Guarenas', models.IntegerField()),
                ('Guarenas_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Guacara', models.IntegerField()),
                ('Guacara_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('La_Vina', models.IntegerField()),
                ('La_Vina_pvp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
