# Generated by Django 4.2.3 on 2024-02-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Barra2',
            field=models.CharField(default='N/A', max_length=20, null=True),
        ),
    ]
