# Generated by Django 4.2.3 on 2024-02-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0002_remove_usuario_sucursal_usuario_sucursal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
