# Generated by Django 4.2.3 on 2024-02-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0002_alter_producto_barra2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Barra2_pvp',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
