# Generated by Django 4.2.3 on 2024-02-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0003_bcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcv',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bcv',
            name='precio',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
