# Generated by Django 4.2.3 on 2024-03-26 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0005_pantalla_codigo_barra_alter_pantalla_id_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
