# Generated by Django 4.2.3 on 2024-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0006_tareaactualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
