# Generated by Django 4.2.3 on 2024-03-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0007_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='sede',
            field=models.DateField(null=True),
        ),
    ]
