# Generated by Django 4.2.3 on 2024-04-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0011_oferta_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='codigo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
