# Generated by Django 4.2.3 on 2024-04-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0012_oferta_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
